### ISSUE TITLE
Bro

### ISSUE THREAD

**Issue by Skidworr** [Daikicalla/EXECollection#1]
### Describe your bug here.

source/PlayState.hx:452: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1210: characters 7-21 : Unknown identifier : sonicHUDStyles
source/PlayState.hx:1212: characters 19-27 : Unknown identifier : hudStyle
source/PlayState.hx:1213: characters 7-15 : Unknown identifier : hudStyle
source/PlayState.hx:1221: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1229: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1237: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1249: characters 5-17 : Unknown identifier : scoreNumbers
source/PlayState.hx:1250: characters 5-13 : Unknown identifier : sonicHUD
source/PlayState.hx:1263: characters 5-17 : Unknown identifier : scoreNumbers
source/PlayState.hx:1264: characters 5-13 : Unknown identifier : sonicHUD
source/PlayState.hx:1276: characters 4-15 : Unknown identifier : missNumbers
source/PlayState.hx:1277: characters 4-12 : Unknown identifier : sonicHUD
source/PlayState.hx:1280: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1281: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1282: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1283: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1284: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1285: characters 3-12 : Unknown identifier : minNumber
source/PlayState.hx:1286: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1295: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1297: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1298: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1299: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1300: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1301: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1302: characters 3-16 : Unknown identifier : secondNumberA
source/PlayState.hx:1303: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1305: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1306: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1307: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1308: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1309: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1310: characters 3-16 : Unknown identifier : secondNumberB
source/PlayState.hx:1311: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:1317: characters 18-26 : Unknown identifier : sonicHUD
source/PlayState.hx:1323: characters 6-19 : Unknown identifier : sonicHUDSongs
source/PlayState.hx:4349: characters 31-43 : Unknown identifier : scoreNumbers
source/PlayState.hx:4386: characters 30-41 : Unknown identifier : missNumbers
source/PlayState.hx:1337: characters 4-12 : Unknown identifier : sonicHUD
source/PlayState.hx:1354: characters 3-11 : Unknown identifier : sonicHUD
source/PlayState.hx:3208: characters 20-28 : Warning : This pattern is unused

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Daikicalla** [comment]
Problem fixed! The variables for all the SonicHUD's were commented, so they technically didn't exist.
